feat: added docker dev and prod files
LainForge/Neura-Launch-Dashboard pull request #19
Opened 2023-10-16 05:30 UTC by TarunTomar122

2023-10-16 08:33 UTC, kunxl-gg requested changes

2023-10-16 08:33 UTC, kunxl-gg commented on .docker/dev/client.dev.Dockerfile
Does this reload whenever the client code is changed. I just see this building once, and serving the build files.

2023-10-16 08:35 UTC, TarunTomar122 commented on .docker/dev/client.dev.Dockerfile
nope. I just copied the original docker file as a placeholder. but with that being said I feel I should do something abt the reloading part at some point

2023-10-18 11:35 UTC, rohansingh9001 approved these changes
I trustie my Bestie.

2023-10-19 05:23 UTC, TarunTomar122 commented on .docker/dev/client.dev.Dockerfile
I'll create an issue for this cz I couldn't make it work myself🥇

2023-10-19 05:23 UTC, merged